### ISSUE TITLE
Multiple errors when (re)starting Modbus Adapter

### ISSUE THREAD

**Issue by FChristian** [ioBroker/ioBroker.modbus#15]
As described here https://forum.iobroker.net/viewtopic.php?f=20&t=14287&p=157772#p157772   , the adapter Version 2.0.3 causes multiple errors and messages in the logfile:

```
modbus.2	2018-06-24 19:54:30.920	info	Connected to slave evcc
sql.0	2018-06-24 19:54:30.463	info	enabled logging of modbus.2.inputRegisters.128_128_total_kwh
sql.0	2018-06-24 19:54:30.445	info	enabled logging of modbus.2.inputRegisters.120_120_W_L1-N
sql.0	2018-06-24 19:54:30.336	info	enabled logging of modbus.2.inputRegisters.100_100_CP-Status
modbus.2	2018-06-24 19:54:30.105	info	starting. Version 2.0.3 in /opt/iobroker/node_modules/iobroker.modbus, node: v6.14.3
host.iobroker	2018-06-24 19:54:28.742	info	instance system.adapter.modbus.2 started with pid 15607
host.iobroker	2018-06-24 19:54:26.348	info	instance system.adapter.modbus.2 terminated with code 0 (OK)
Caught	2018-06-24 19:54:26.347	error	by controller[0]: at processImmediate [as _immediateCallback] (timers.js:617:5)
Caught	2018-06-24 19:54:26.347	error	by controller[0]: at tryOnImmediate (timers.js:645:5)
Caught	2018-06-24 19:54:26.347	error	by controller[0]: at runCallback (timers.js:672:20)
Caught	2018-06-24 19:54:26.347	error	by controller[0]: at Immediate.setImmediate (/opt/iobroker/node_modules/iobroker.modbus/lib/master.js:180:21)
Caught	2018-06-24 19:54:26.346	error	by controller[0]: at pollFloatBlock (/opt/iobroker/node_modules/iobroker.modbus/lib/master.js:142:20)
Caught	2018-06-24 19:54:26.345	error	by controller[0]: at err (/opt/iobroker/node_modules/iobroker.modbus/lib/master.js:195:21)
Caught	2018-06-24 19:54:26.345	error	by controller[0]: at err (/opt/iobroker/node_modules/iobroker.modbus/lib/master.js:310:33)
Caught	2018-06-24 19:54:26.345	error	by controller[0]: at pollFloatsBlocks (/opt/iobroker/node_modules/iobroker.modbus/lib/master.js:191:13)
Caught	2018-06-24 19:54:26.345	error	by controller[0]: at pollFloatBlock (/opt/iobroker/node_modules/iobroker.modbus/lib/master.js:152:21)
Caught	2018-06-24 19:54:26.344	error	by controller[0]: 2018-06-24 19:54:26.275 - error: modbus.2 TypeError: Cannot read property 'readHoldingRegisters' of null
Caught	2018-06-24 19:54:26.344	error	by controller[0]: 2018-06-24 19:54:26.272 - modbus.2 uncaught exception: Cannot read property 'readHoldingRegisters' of null
Caught	2018-06-24 19:54:26.344	error	by controller[0]: at processImmediate [as _immediateCallback] (timers.js:617:5)
Caught	2018-06-24 19:54:26.344	error	by controller[0]: at tryOnImmediate (timers.js:645:5)
Caught	2018-06-24 19:54:26.342	error	by controller[0]: at runCallback (timers.js:672:20)
Caught	2018-06-24 19:54:26.342	error	by controller[0]: at Immediate.setImmediate (/opt/iobroker/node_modules/iobroker.modbus/lib/master.js:180:21)
Caught	2018-06-24 19:54:26.342	error	by controller[0]: at pollFloatBlock (/opt/iobroker/node_modules/iobroker.modbus/lib/master.js:142:20)
Caught	2018-06-24 19:54:26.342	error	by controller[0]: at err (/opt/iobroker/node_modules/iobroker.modbus/lib/master.js:195:21)
Caught	2018-06-24 19:54:26.342	error	by controller[0]: at err (/opt/iobroker/node_modules/iobroker.modbus/lib/master.js:310:33)
Caught	2018-06-24 19:54:26.341	error	by controller[0]: at pollFloatsBlocks (/opt/iobroker/node_modules/iobroker.modbus/lib/master.js:191:13)
Caught	2018-06-24 19:54:26.341	error	by controller[0]: at pollFloatBlock (/opt/iobroker/node_modules/iobroker.modbus/lib/master.js:152:21)
Caught	2018-06-24 19:54:26.340	error	by controller[0]: TypeError: Cannot read property 'readHoldingRegisters' of null
host.iobroker	2018-06-24 19:54:26.208	info	stopInstance system.adapter.modbus.2 killing pid 1493
host.iobroker	2018-06-24 19:54:26.207	info	stopInstance system.adapter.modbus.2
host.iobroker	2018-06-24 19:54:26.206	info	object change system.adapter.modbus.2`
```
Environment Data:
root@iobroker:~# cat /proc/version
Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.51-3 (2017-12-13)
root@iobroker:~# npm -v
3.10.10
root@iobroker:~# node -v
v6.14.2
root@iobroker:~# nodejs -v
v6.14.2

**Comment by mcstumpfi** [comment]
Heyy there, i Use it with Wago and tried already different Version. Even with 1.1.0 i have these error sometimes after changing Modbus Variables.
I can't get the newest Version to start.
