### ISSUE TITLE
Probleme mit serieller Verbindung

### ISSUE THREAD

**Issue by ykuendig** [ioBroker/ioBroker.modbus#3]
Der Adapter 0.4.7 und aber auch 0.4.9 machten mir Probleme bei der Verbindung zum USB-RD485-Converter.  Das bild zeigte sich so, oder so ähnlich:

>host.raspi3   2017-02-01 01:46:15.092   info   Do not restart adapter system.adapter.modbus.0 because disabled or deleted
host.raspi3   2017-02-01 01:46:15.084   error   instance system.adapter.modbus.0 terminated with code 3 (Adapter disabled or invalid config)
host.raspi3   2017-02-01 01:45:50.362   info   "system.adapter.modbus.0" disabled
host.raspi3   2017-02-01 01:45:50.361   info   object change system.adapter.modbus.0
host.raspi3   2017-02-01 01:45:49.076   info   instance system.adapter.javascript.0 terminated with code 0 (OK)
javascript.0   2017-02-01 01:45:49.016   info   Adapter is disabled => stop
host.raspi3   2017-02-01 01:45:48.993   info   stopInstance system.adapter.javascript.0 killing pid 30477
host.raspi3   2017-02-01 01:45:48.992   info   stopInstance system.adapter.javascript.0
host.raspi3   2017-02-01 01:45:48.988   info   "system.adapter.javascript.0" disabled
host.raspi3   2017-02-01 01:45:48.987   info   object change system.adapter.javascript.0
host.raspi3   2017-02-01 01:45:41.861   info   Restart adapter system.adapter.modbus.0 because enabled
host.raspi3   2017-02-01 01:45:41.860   error   instance system.adapter.modbus.0 terminated with code 0 (OK)
modbus.0   2017-02-01 01:45:41.795   info   terminating
modbus.0   2017-02-01 01:45:41.750   error   at Socket.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
modbus.0   2017-02-01 01:45:41.750   error   at Socket. (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)
modbus.0   2017-02-01 01:45:41.750   error   at Manager.ondata (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:322:16)
modbus.0   2017-02-01 01:45:41.750   error   at Decoder.add (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/socket.io-parser/index.js:246:12)
modbus.0   2017-02-01 01:45:41.750   error   at Decoder.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
modbus.0   2017-02-01 01:45:41.750   error   at Decoder. (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)
modbus.0   2017-02-01 01:45:41.750   error   at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:332:8)
modbus.0   2017-02-01 01:45:41.750   error   at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
modbus.0   2017-02-01 01:45:41.750   error   at Manager. (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)
modbus.0   2017-02-01 01:45:41.750   error   at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:236:12)
modbus.0   2017-02-01 01:45:41.750   error   at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:312:9)
modbus.0   2017-02-01 01:45:41.750   error   at Socket. (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1253:35)
modbus.0   2017-02-01 01:45:41.750   error   at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1365:21
modbus.0   2017-02-01 01:45:41.750   error   at /opt/iobroker/node_modules/iobroker.modbus/main.js:1332:13
modbus.0   2017-02-01 01:45:41.750   error   at clear (/opt/iobroker/node_modules/iobroker.modbus/main.js:1328:22)
modbus.0   2017-02-01 01:45:41.750   error   at Object.main.start (/opt/iobroker/node_modules/iobroker.modbus/main.js:1740:25)
modbus.0   2017-02-01 01:45:41.750   error   TypeError: Cannot read property 'on' of null
modbus.0   2017-02-01 01:45:41.736   error   uncaught exception: Cannot read property 'on' of null
modbus.0   2017-02-01 01:45:41.720   error   Cannot open port "/dev/ttyUSB0" [9600]: TypeError: Cannot read property 'complete' of undefined
modbus.0   2017-02-01 01:45:40.406   info   starting. Version 0.4.7 in /opt/iobroker/node_modules/iobroker.modbus, node: v4.7.2
...
...
modbus.0   2017-02-01 01:44:25.958   info   List of port: [{"comName":"/dev/ttyAMA0"},{"comName":"/dev/ttyUSB0","manufacturer":"FTDI","serialNumber":"FTDI_FT232R_USB_UART_A603O55Y","pnpId":"usb-FTDI_FT232R_USB_UART_A603O55Y-if00-port0","vendor...`

Eine kleine Korrektur schaffte Abhilfe.
in der Datei /lib/modbus-serial-client.js habe ich die Zeile 174 entfernt:
>173:            serialport.close();
174:            //serialport = null;

Keine Ahnung wie wichtig / richtig das ist... Aber nun läufts recht stabil.

**Comment by ykuendig** [comment]
Schaut so aus als obs ab 0.4.10 läuft. 
Ich mach dann hier mal zu.
